#!/bin/env bash
_REVERT(){
  for f in home/.zshrc.backup home/.termux/colors.properties.backup home/.termux/termux.properties.backup usr/etc/motd.backup usr/etc/zshrc.backup usr/etc/bash.bashrc.backup; do 
    if [ -f $f ]; then 
      mv $f $(echo ${f/.backup/})
    fi 
  done
}

_REVERT
